In [1]:
import pandas as pd
import numpy as np
#from ydata_profiling import ProfileReport

df = pd.read_csv('star_classification.csv')
df.head()

obj_ID       alpha      delta         u         g         r  \
0  1.237661e+18  135.689107  32.494632  23.87882  22.27530  20.39501   
1  1.237665e+18  144.826101  31.274185  24.77759  22.83188  22.58444   
2  1.237661e+18  142.188790  35.582444  25.26307  22.66389  20.60976   
3  1.237663e+18  338.741038  -0.402828  22.13682  23.77656  21.61162   
4  1.237680e+18  345.282593  21.183866  19.43718  17.58028  16.49747   

          i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
0  19.16573  18.79371    3606       301        2        79  6.543777e+18   
1  21.16812  21.61427    4518       301        5       119  1.176014e+19   
2  19.34857  18.94827    3606       301        2       120  5.152200e+18   
3  20.50454  19.25010    4192       301        3       214  1.030107e+19   
4  15.97711  15.54461    8102       301        3       137  6.891865e+18   

    class  redshift  plate    MJD  fiber_ID  
0  GALAXY  0.634794   5812  56354       171  
1  GALAXY  0.779136  10445  58158       427  
2  GALAXY  0.644195   4576  55592       299  
3  GALAXY  0.932346   9149  58039       775  
4  GALAXY  0.116123   6121  56187       842

In [2]:
df.shape

(100000, 18)

In [3]:
df.isna().sum()

obj_ID         0
alpha          0
delta          0
u              0
g              0
r              0
i              0
z              0
run_ID         0
rerun_ID       0
cam_col        0
field_ID       0
spec_obj_ID    0
class          0
redshift       0
plate          0
MJD            0
fiber_ID       0
dtype: int64

In [4]:
df.dtypes

obj_ID         float64
alpha          float64
delta          float64
u              float64
g              float64
r              float64
i              float64
z              float64
run_ID           int64
rerun_ID         int64
cam_col          int64
field_ID         int64
spec_obj_ID    float64
class           object
redshift       float64
plate            int64
MJD              int64
fiber_ID         int64
dtype: object

In [5]:
df['class'].unique()

array(['GALAXY', 'QSO', 'STAR'], dtype=object)

In [6]:
df['class'].value_counts()

GALAXY    59445
STAR      21594
QSO       18961
Name: class, dtype: int64

In [7]:
#profile = ProfileReport(df,title="Star Profile Report")
#profile

In [8]:
odd = df.loc[df['u'] == -9999]
odd

obj_ID       alpha     delta       u       g        r         i  \
79543  1.237649e+18  224.006526 -0.624304 -9999.0 -9999.0  18.1656  18.01675   

            z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID class  \
79543 -9999.0     752       301        2       537  3.731277e+18  STAR   

       redshift  plate    MJD  fiber_ID  
79543  0.000089   3314  54970       162

In [9]:
odd1 = df.loc[df['g'] == -9999]
odd1

obj_ID       alpha     delta       u       g        r         i  \
79543  1.237649e+18  224.006526 -0.624304 -9999.0 -9999.0  18.1656  18.01675   

            z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID class  \
79543 -9999.0     752       301        2       537  3.731277e+18  STAR   

       redshift  plate    MJD  fiber_ID  
79543  0.000089   3314  54970       162

In [10]:
odd2 = df.loc[df['r'] == -9999]
odd2

Empty DataFrame
Columns: [obj_ID, alpha, delta, u, g, r, i, z, run_ID, rerun_ID, cam_col, field_ID, spec_obj_ID, class, redshift, plate, MJD, fiber_ID]
Index: []

In [11]:
odd3 = df.loc[df['i'] == -9999]
odd3

Empty DataFrame
Columns: [obj_ID, alpha, delta, u, g, r, i, z, run_ID, rerun_ID, cam_col, field_ID, spec_obj_ID, class, redshift, plate, MJD, fiber_ID]
Index: []

In [12]:
odd4 = df.loc[df['z'] == -9999]
odd4

obj_ID       alpha     delta       u       g        r         i  \
79543  1.237649e+18  224.006526 -0.624304 -9999.0 -9999.0  18.1656  18.01675   

            z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID class  \
79543 -9999.0     752       301        2       537  3.731277e+18  STAR   

       redshift  plate    MJD  fiber_ID  
79543  0.000089   3314  54970       162

In [13]:
df = df.drop(df.index[79543], axis=0)
df.shape

(99999, 18)

In [14]:
df = df.reset_index(drop=True)

In [15]:
df['rerun_ID'].unique()

array([301], dtype=int64)

In [16]:
df = df.drop(columns = ['rerun_ID'],axis=1)

In [17]:
df_train = df.sample(frac=0.9, random_state=25)
df_test = df.drop(df_train.index)
print(df_train.shape)
print(df_test.shape)

(89999, 17)
(10000, 17)


In [18]:
df_train1 = df_train.sample(frac=0.8, random_state=20)
df_val = df_train.drop(df_train1.index)
print(df_train1.shape)
print(df_val.shape)

(71999, 17)
(18000, 17)


In [19]:
t = {'GALAXY':0,'QSO':1,'STAR':2}

In [20]:
df_train['class_enc'] = df_train['class'].map(t)
df_val['class_enc'] = df_val['class'].map(t)
df_train.head()

obj_ID       alpha      delta         u         g         r  \
94457  1.237668e+18  172.427892  18.790452  24.64223  22.25799  21.90783   
20973  1.237665e+18  162.876293  31.838297  22.36357  21.53171  21.15401   
42832  1.237660e+18   54.185294   0.977728  21.11077  18.74387  17.50812   
1568   1.237665e+18  144.515185  31.113963  23.00851  22.65649  22.50306   
41003  1.237663e+18  331.238887   0.201204  22.90914  21.54735  21.17424   

              i         z  run_ID  cam_col  field_ID   spec_obj_ID   class  \
94457  21.04677  20.68865    5313        2        87  6.619268e+18    STAR   
20973  21.03201  20.55818    4576        1       323  7.256622e+18     QSO   
42832  17.01411  16.77351    3438        6       161  8.254125e+18    STAR   
1568   22.07332  21.45145    4518        5       117  1.176015e+19  GALAXY   
41003  20.81643  20.60504    4192        4       164  1.032006e+19     QSO   

       redshift  plate    MJD  fiber_ID  class_enc  
94457  0.000381   5879  56047       372          2  
20973  2.147799   6445  56366       718          1  
42832  0.000081   7331  56658       556          2  
1568   0.832558  10445  58158       467          0  
41003  3.176916   9166  58051       205          1

In [21]:
df_train = df_train.drop(['class'],axis=1)
df_val = df_val.drop(['class'], axis=1)
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [22]:
df_val.head()

obj_ID       alpha      delta         u         g         r  \
0  1.237668e+18  172.427892  18.790452  24.64223  22.25799  21.90783   
1  1.237663e+18  331.238887   0.201204  22.90914  21.54735  21.17424   
2  1.237658e+18  141.637279  42.088899  25.03010  23.79241  21.48902   
3  1.237668e+18   84.873591  -2.153757  21.72150  21.17631  19.22806   
4  1.237679e+18  321.649375   2.096375  21.25759  20.10503  20.81921   

          i         z  run_ID  cam_col  field_ID   spec_obj_ID  redshift  \
0  21.04677  20.68865    5313        2        87  6.619268e+18  0.000381   
1  20.81643  20.60504    4192        4       164  1.032006e+19  3.176916   
2  20.47543  19.81643    2830        1       215  9.342972e+18  0.595731   
3  18.42299  17.82802    5181        6        89  8.172984e+18  0.277057   
4  20.29224  19.06567    7712        4        73  1.031569e+19  0.219943   

   plate    MJD  fiber_ID  class_enc  
0   5879  56047       372          2  
1   9166  58051       205          1  
2   8298  57390       927          0  
3   7259  56603       278          0  
4   9162  58040       702          0

In [23]:
df_test['class_enc'] = df_test['class'].map(t)
df_test = df_test.drop(columns=['class'],axis=1)

In [24]:
df_train['class_enc'].value_counts()

0    53547
2    19414
1    17038
Name: class_enc, dtype: int64

In [25]:
df_com = pd.concat([df_train,df_val])
df_com.shape

(107999, 17)

In [26]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()

X = df_com.drop(columns=['class_enc'],axis=1)
y = df_com['class_enc']

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(X)
X = pd.DataFrame(ss.transform(X))

In [27]:
from tensorflow.keras.utils import to_categorical

y_cat = to_categorical(y)

In [28]:
y_cat

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [29]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X.values,y_cat, test_size=0.2) 

In [30]:
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

#model = keras.Sequential()
#model.add(keras.layers.InputLayer(input_shape=(16,)))
#model.add(keras.layers.Dense(30, activation='relu'))
#model.add(keras.layers.Dense(3, activation='softmax'))

#early_stopping = EarlyStopping(patience=5, restore_best_weights=True)

In [31]:
#model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])
#history = model.fit(x_train, y_train, epochs=1000, batch_size=512, validation_data=(x_test, y_test), callbacks=[early_stopping])


In [32]:
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# Define your model architecture
model = keras.Sequential([
    keras.layers.Dense(35, activation="relu", input_shape=(16,)),
    keras.layers.Dense(3, activation="softmax")
])

In [33]:
# Compile the model
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.009833213151263778),
              loss="categorical_crossentropy",
              metrics=["accuracy"])

In [34]:
# Train the model
model.fit(x_train, y_train, epochs=150, batch_size=512,
                    validation_data=(x_test, y_test),
                    callbacks=[keras.callbacks.EarlyStopping(patience=5)])

Epoch 1/150
169/169 [==============================] - 2s 5ms/step - loss: 0.3299 - accuracy: 0.8854 - val_loss: 0.1838 - val_accuracy: 0.9425
Epoch 2/150
169/169 [==============================] - 1s 4ms/step - loss: 0.1653 - accuracy: 0.9494 - val_loss: 0.1433 - val_accuracy: 0.9549
Epoch 3/150
169/169 [==============================] - 1s 4ms/step - loss: 0.1430 - accuracy: 0.9573 - val_loss: 0.1311 - val_accuracy: 0.9611
Epoch 4/150
169/169 [==============================] - 1s 3ms/step - loss: 0.1327 - accuracy: 0.9604 - val_loss: 0.1242 - val_accuracy: 0.9619
Epoch 5/150
169/169 [==============================] - 1s 3ms/step - loss: 0.1277 - accuracy: 0.9618 - val_loss: 0.1208 - val_accuracy: 0.9630
Epoch 6/150
169/169 [==============================] - 1s 4ms/step - loss: 0.1226 - accuracy: 0.9629 - val_loss: 0.1151 - val_accuracy: 0.9649
Epoch 7/150
169/169 [==============================] - 1s 4ms/step - loss: 0.1188 - accuracy: 0.9645 - val_loss: 0.1119 - val_accuracy: 0.9645

In [35]:
# Evaluate the model

test_x = df_test.drop(columns=['class_enc'],axis=1)
test_y = df_test[['class_enc']]

test_x = ss.transform(test_x)

pred = model.predict(test_x)
pred

313/313 [==============================] - 0s 917us/step


array([[9.9468452e-01, 5.3154770e-03, 2.8322357e-19],
       [9.9465430e-01, 5.3457050e-03, 3.3736564e-34],
       [9.9789584e-01, 2.1041820e-03, 3.7925698e-18],
       ...,
       [5.0028875e-03, 9.9499714e-01, 0.0000000e+00],
       [9.3609527e-02, 9.0639055e-01, 1.3665983e-31],
       [9.9904090e-01, 9.5906825e-04, 1.1006313e-23]], dtype=float32)

In [36]:
sd=[]
for i in range(len(pred)):
    sd.append(np.argmax(pred[i]))

from sklearn.metrics import accuracy_score


accuracy_score(test_y,sd) 

0.9674

In [37]:
import tensorflow as tf
# Save the model
model.save('model.h5')

In [38]:
# Load the model
loaded_model = tf.keras.models.load_model('model.h5')

In [39]:
predictions = loaded_model.predict(test_x)

313/313 [==============================] - 0s 914us/step


In [41]:
import joblib
joblib.dump(ss, 'scaling.pkl')

['scaling.pkl']